### PR TITLE
Added basis universal compressed KTX2 texture files

### PR DESCRIPTION
**Pull request by SaschaWillems**
This PR adds a set of basis universal compressed KTX2 textures. Each texture comes in two versions, one using UASTC and ETC1S texture compression methods.

This PR is the base for an upcoming basis universal texture compression sample on the Vulkan samples repo.

### CODE REVIEW

**Review by gpx1000 — APPROVED** [review]
lgtm

**Review by gpx1000 — APPROVED** [review]
works in linux

**Review by gary-sweet — APPROVED** [review]

**Comment by TomAtkinsonArm** [comment]
Will approve after I am added to the project :)

**Review by TomAtkinsonArm — APPROVED** [review]

**Comment by gary-sweet** [comment]
Since the samples PR that uses this has been merged, we really should merge this too. The sample just looks broken unless you know to pull this PR.

**Pull request merged**
